"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { useState } from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Auth",
// 	description: "Generated by create next app",
// };

const navLinks = [
	{ name: "Register", href: "/register" },
	{ name: "Login", href: "/login" },
	{ name: "Forgot Password", href: "/forgot-password" },
];

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [inp, setInput] = useState<string>("");
	console.log(inp);
	console.info("render layout");

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div
					style={{
						backgroundColor: "blue",
						padding: "1rem",
						gap: "1rem",
						flexDirection: "row",
						display: "felx",
					}}
				>
					<input
						onChange={(e) => setInput(e.target.value)}
						value={inp}
						placeholder="masuk pa ekon"
					/>

					{navLinks.map(({ name, href }) => (
						<Link
							key={name}
							href={href}
							style={{ marginRight: "1rem" }}
						>
							{name}
						</Link>
					))}
				</div>
				{children}
			</body>
		</html>
	);
}
