import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProviderContext } from "./components/ProviderContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

/**
 * meta data have 2 ways in next js, put in root layout or page
 * when we put in root layout all routes will applies with this meata data
 * when use meta data in page it will be specified for that page route
 * but when we hae meatadata in layout and page to, the priority will be used with metadata page route
 * all meta data filled in page will be overwritten in  metadata root layout
 * ! meta data just allowed in server component
 */

export const metadata: Metadata = {
	title: {
		default: "Default Next js",
		template: "%s Next js",
		// aboslute for another layout or page meta data using outside metadata root
	},
	description: "Generated by create next app",
};

/**
 *
 * could make multiple root layout, so this is very dynamic
 */
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ProviderContext>{children}</ProviderContext>
				{/* {children} */}
				<footer
					style={{
						backgroundColor: "yellow",
						padding: "1rem",
						color: "black",
					}}
				>
					footer
				</footer>
			</body>
		</html>
	);
}
